# Generated by Django 3.2.5 on 2021-07-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_notegroup_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notegroup',
            name='group_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
