# Generated by Django 3.2.5 on 2021-07-18 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210718_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snote',
            name='to_whom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toWhom', to=settings.AUTH_USER_MODEL),
        ),
    ]
