# Generated by Django 3.2.5 on 2021-07-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_snote_to_whom'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group_admin',
            field=models.BooleanField(default=False),
        ),
    ]
