# Generated by Django 3.2.5 on 2021-08-26 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0006_auto_20210826_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='notegroup',
            name='members',
            field=models.ManyToManyField(related_name='members', through='notes.GroupColor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notegroup',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
