# Generated by Django 3.2.5 on 2021-08-26 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0007_auto_20210826_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notegroup',
            name='members',
            field=models.ManyToManyField(related_name='members_groups', through='notes.GroupColor', to=settings.AUTH_USER_MODEL),
        ),
    ]
