# Generated by Django 3.2.5 on 2021-08-26 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0008_alter_notegroup_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupColor',
            new_name='Membership',
        ),
    ]
