# Generated by Django 3.2.5 on 2021-08-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20210826_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
