# Generated by Django 3.2.5 on 2021-08-28 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20210828_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='color',
            field=models.CharField(default='fdd663', max_length=6),
        ),
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='notes.group'),
        ),
    ]
